const kBaseUrl = "http://62.72.44.247/api";
const kImageBaseUrl = "http://62.72.44.247";
const kProductsUrl = "$kBaseUrl/products/";
const kProductUrl = "$kBaseUrl/products/?id=";
const kSearchProductUrl = "$kBaseUrl/products/?search_query=";
const kCustomersUrl = "$kBaseUrl/customers/";
const kCustomerUrl = "$kBaseUrl/customers/?id=";
const kSearchCustomerUrl = "$kBaseUrl/customers/?search_query=";
const kOrdersUrl = "$kBaseUrl/orders/";